############################################
#
# Documentation for EventDataFilter: https://docs.citrix.com/en-us/uberagent/current-release/uxm-features-configuration/event-data-filtering/
#
############################################

##############################################################
#
# Clear extended process info for receivers with EnableExtendedInfo disabled
#
##############################################################

[EventDataFilter]
Action = clear
Sourcetype = Process:ProcessDetail
Sourcetype = Process:ProcessStartup
Sourcetype = Application:Errors
Sourcetype = Process:DnsQuery
Sourcetype = Process:ProcessStatistics
Field = ProcID
Field = ProcGUID
Field = ProcParentID
Field = SessionID
Field = SessionGUID
Field = ProcParentName
Field = ProcPath
Field = ProcCmdline
Query = Receiver.EnableExtendedInfo == false

# Citrix event data filter
@ConfigInclude "Event data filter/uberAgent-eventdata-filter-citrix-Windows.conf" platform=Windows
@ConfigInclude "Event data filter/uberAgent-eventdata-filter-citrix-macOS.conf" platform=macOS
@ConfigInclude "Event data filter/uberAgent-eventdata-filter-citrix-Linux.conf" platform=Linux

# Citrix DNS exclusions
@ConfigInclude "Event data filter/uberAgent-eventdata-filter-citrix-DNS.conf" platform=Windows
@ConfigInclude "Event data filter/uberAgent-eventdata-filter-citrix-DNS.conf" platform=macOS
