#
# If Citrix Experience Insights is configured using Group Policy,
# this file is included and processed by default to include additional configuration elements,
# that are not available in Group Policy configurations.
#

# Include the Security capability config file
@ConfigInclude ESA/uberAgent-ESA.conf platform=Windows

# Include default event data filter rules
@ConfigInclude "Event data filter/uberAgent-eventdata-filter.conf"
