#
# This is the main configuration file for Citrix Experience Insights - Security.
# It is only required if the Security capability is enabled.
#

############################################
#
# Includes (config files to be processed, too)
#
############################################

# Citrix Threat Detection rules
@ConfigInclude ESA/uberAgent-ESA-am-citrix.conf

# Sigma process creation rules with level critical
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-critical-common.conf"
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-critical-macos.conf" platform=MacOS
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-critical-windows.conf" platform=Windows

# Sigma process creation rules with level high
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-high-common.conf"
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-high-macos.conf" platform=MacOS
@ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-high-windows.conf" platform=Windows

# Sigma process creation rules with level medium. Uncomment the next line to enable.
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-medium-common.conf"
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-medium-macos.conf" platform=MacOS
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-medium-windows.conf" platform=Windows

# Sigma process creation rules with level low. Uncomment the next line to enable.
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-low-common.conf"
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-low-macos.conf" platform=MacOS
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-low-windows.conf" platform=Windows

# Sigma process creation rules with level informational. Uncomment the next line to enable.
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-informational-common.conf"
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-informational-macos.conf" platform=MacOS
# @ConfigInclude "ESA/Sigma rules/uberAgent-ESA-am-sigma-informational-windows.conf" platform=Windows

# Citrix Security & Compliance Inventory checks
@ConfigInclude ESA/uberAgent-ESA-si-citrix-windows.conf platform=Windows
@ConfigInclude ESA/uberAgent-ESA-si-citrix-macos.conf platform=macOS

# Event log configuration
@ConfigInclude ESA/uberAgent-ESA-eventlog.conf
